version: '2'

services:
    api:
        image: toddlamothe/beerdb-services
        ports:
            - "8888:80"
    web:
        image: toddlamothe/beerdb-web
        ports:
            - "8002:80"
networks:
  default:
    external:
      name: nat
